### ISSUE TITLE
Websocket Server Rejecting Traffic from Localhost:3000

### ISSUE THREAD

**Issue by csjoblom** [ryanrolds/club#28]
I currently get the following error when attempting to connect to localhost:3001/room:

club_1      | {"file":"server.go:29","func":"ServeHTTP","level":"error","msg":"problem upgrading to websockets: websocket: request origin not allowed by Upgrader.CheckOrigin","time":"2020-05-26T06:33:33Z"}

This is when I'm on localhost:3000 for frontend. 

Steps to reproduce:
* Fresh Repo
* Hard Code localhost:3001/room into examples for singaling ws
* make run in main directory
* Once build is complete, you'll notice the error logged in your console. 

I'm kinda brain dumping since its the end of the night.

**Comment by tsmada** [comment]
@csjoblom it looks like the gorilla library that implements golang websockets requires some defaults:

The Upgrader calls the function specified in the CheckOrigin field to check the origin. If the CheckOrigin function returns false, then the Upgrade method fails the WebSocket handshake with HTTP status 403.

If the CheckOrigin field is nil, then the Upgrader uses a safe default: fail the handshake if the Origin request header is present and the Origin host is not equal to the Host request header.

https://www.gorillatoolkit.org/pkg/websocket
https://github.com/gorilla/websocket/issues/398
https://github.com/gorilla/websocket/issues/367

I've submitted a fix for this: https://github.com/tsmada/club/tree/go-origin-check

Take a look when you get a minute. We'll want Ryan and others to weigh in here on how we want to handle specific origins (CORS?).

**Comment by csjoblom** [comment]
Looks like we good, thanks @tsmada
